baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Puzzmo Blog'
theme = 'paper'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'puzzmotoday'               # twitter.com/YOUR_TWITTER_ID
  github = 'puzzmo-com'                 # github.com/YOUR_GITHUB_ID
  instagram = 'puzzmo'           # instagram.com/YOUR_INSTAGRAM_ID
#   linkedin = 'company/puzzmo'             # linkedin.com/in/YOUR_LINKEDIN_ID
#   mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon



  # misc
#   disableHLJS = true                        # disable highlight.js
#   disablePostNavigation = true              # disable post navigation
#   monoDarkIcon = true                       # show monochrome dark mode icon
#   gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
#   graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
#   math = true                               # enable KaTeX math typesetting globally

  # giscus
[params.giscus]
  repo = 'puzzmo-com/blog.puzzmo.com'                 # see https://giscus.app for more details
  repoId = 'R_kgDOK5Q10A'
  category = 'Blog Posts'
  categoryId = 'DIC_kwDOK5Q10M4CbtK1'
  mapping = 'pathname'
  theme = 'light'
  lang = 'en'